# Generated by Django 2.2.6 on 2020-04-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identitecomplete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cni',
            old_name='CNI_number',
            new_name='CNI_number_CNI',
        ),
        migrations.RenameField(
            model_name='completeidentity',
            old_name='CNI_number',
            new_name='CNI_number_cp',
        ),
    ]
