# Generated by Django 2.2.6 on 2020-04-20 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identitecomplete', '0003_auto_20200420_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communeleader',
            name='commune_leaded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identitecomplete.Commune'),
        ),
        migrations.AlterField(
            model_name='provinceleader',
            name='province_leaded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identitecomplete.Province'),
        ),
    ]
